# Generated by Django 4.2 on 2025-07-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0002_alter_abastecimento_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abastecimento',
            old_name='litros_consumido',
            new_name='litros_abastecidos',
        ),
    ]
